apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-kyxr
  namespace: jephilli-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:d9d23d2592e48f598a5027e68a388dff16bcc89e1b59b4b72751fc041fc23377
        name: my-go
        resources: {}
status: {}
